### ISSUE TITLE
Provide an RSS or Atom feed for the blog

### ISSUE THREAD

**Issue by Minoru** [matt-noonan/storm-country#1]
Hello! Very interested in your upcoming "GOF patterns in Haskell" series. To make it easier to follow your posts, can you please provide an RSS or Atom feed? It's a simple XML file with a list of all your posts.

I couldn't find any mentions of RSS in relation to Happstack, but you can certainly take a look at [Hakyll's implementation](https://github.com/jaspervdj/hakyll/blob/master/lib/Hakyll/Web/Feed.hs) for inspiration.

**Comment by matt-noonan** [comment]
Great idea, I should be able to add it in short order.

**Comment by matt-noonan** [comment]
Ok, it should now be available at http://storm-country.com/rss. Please let me know if this does not work, or auto-detection fails for some page. Thanks!

**Comment by Minoru** [comment]
It works; thank you! Note that headline-only feeds might annoy some people, because they'll have to click through to your site instead of reading everything in their favourite RSS reader.
